name: "Search for README.md"

description: "Check for a README file in the current repository"

inputs:
  repo-token:
    description: "token that gives permission to search through repo"
    # required: true

runs:
  using: "node12"
  main: "main.js"